In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [7]:
import pandas as pd
df = pd.read_csv("Uber_Eats_data.csv")
df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [4]:
df.shape

(23193, 13)

In [5]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [6]:
df['votes'] = pd.to_numeric(df['votes'], errors='coerce')

In [13]:
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].astype(str)
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].str.replace(',', '').str.strip()
df['approx_cost(for two people)'] = pd.to_numeric(df['approx_cost(for two people)'], errors='coerce')

In [14]:
df['rate'] = df['rate'].astype(str)
df['rate'] = df['rate'].str.replace('/5', '').str.strip()
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  object
 1   online_order                 23193 non-null  object
 2   book_table                   23193 non-null  object
 3   rate                         23046 non-null  float64
 4   votes                        23193 non-null  int64
 5   phone                        23193 non-null  object
 6   location                     23193 non-null  object
 7   rest_type                    23193 non-null  object
 8   dish_liked                   23193 non-null  object
 9   cuisines                     23193 non-null  object
 10  approx_cost(for two people)  23193 non-null  int64
 11  listed_in(type)              23193 non-null  object
 12  listed_in(city)              23193 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 2.3+ MB

In [16]:
df.isnull().sum()

name                             0
online_order                     0
book_table                       0
rate                           147
votes                            0
phone                            0
location                         0
rest_type                        0
dish_liked                       0
cuisines                         0
approx_cost(for two people)      0
listed_in(type)                  0
listed_in(city)                  0
dtype: int64

In [17]:
df = df.dropna(subset=['rate'])

In [18]:
df['rate'].isnull().sum()

np.int64(0)

In [19]:
df.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(34)

In [22]:
df[df.duplicated()]

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
1532,The Fisherman's Wharf,Yes,Yes,4.4,4099,080 49653108,Sarjapur Road,"Casual Dining, Bar","Sea Food, Caesar Salad, Jumbo Prawns, Cocktail...","Seafood, Goan, North Indian, Continental, Asian",1400,Buffet,Bellandur
1998,OPUS Club,No,Yes,4.4,1496,+91 8046444777\r\n+91 7349734900,Sarjapur Road,Pub,"Biryani, Cocktails, Nachos, Mocktails, Long Is...","Continental, Italian, North Indian, Mexican",1900,Drinks & nightlife,Bellandur
1999,Float,Yes,Yes,4.4,3061,+91 9066887042\r\n+91 9066887086,Marathahalli,"Casual Dining, Bar","Butter Fish, Chicken Burritos, Cocktails, Mock...","North Indian, Japanese",1500,Drinks & nightlife,Bellandur
2015,Float,Yes,Yes,4.4,3061,+91 9066887042\r\n+91 9066887086,Marathahalli,"Casual Dining, Bar","Butter Fish, Chicken Burritos, Cocktails, Mock...","North Indian, Japanese",1500,Pubs and bars,Bellandur
2887,Fava,No,Yes,4.4,2039,080 49652925,Lavelle Road,"Casual Dining, Bar","Gnocchi, Cocktails, Pizza, Salads, Creme Brule...","Healthy Food, Mediterranean, Desserts, Italian...",1200,Drinks & nightlife,Brigade Road
4243,Vyanjan,Yes,No,3.9,201,+91 9916937446,BTM,Quick Bites,"Poha, Jalebi, Paratha, Bhindi Masala, Kachori,...","North Indian, Street Food",300,Delivery,BTM
4244,Mid Night Hunting,Yes,No,3.7,127,+91 8892140430,Ejipura,"Takeaway, Delivery","Burgers, Chicken Burger, Pasta, Chicken Pizza","Fast Food, Italian",300,Delivery,BTM
4245,Carrots,Yes,Yes,4.1,600,080 41172812,Koramangala 6th Block,Casual Dining,"Pizza, Pasta, Salads, Masala Chai, Soya Butter...","Italian, North Indian, Healthy Food, Desserts",1100,Delivery,BTM
4246,Rolls & Co,Yes,No,3.9,213,+91 7353848635,Koramangala 6th Block,Quick Bites,"Rolls, Chicken Wings, Shawarma, Chicken Tikka ...","Burger, Beverages, Rolls",400,Delivery,BTM
4973,Fenny's Lounge And Kitchen,No,Yes,4.5,6349,080 49653085,Koramangala 7th Block,"Bar, Casual Dining","Caramel Pudding, Cocktails, Pizza, Mocktails, ...","Mediterranean, Pizza, Continental, Seafood, Salad",1600,Pubs and bars,BTM
5401,Laughing Llama Gastropub,Yes,Yes,4.3,394,+91 9535029732,Brigade Road,"Bar, Casual Dining","Pancakes, Cocktails, Biryani, Draught Beer, Lo...","Finger Food, Continental, Pizza",1600,Delivery,Church Street
5402,The Bundle Co.,Yes,No,4.4,223,+91 9148887222,MG Road,Quick Bites,"Burgers, Salad, Mocktails, Pasta Arrabiata, Fr...","Burger, Continental, Italian, Beverages",700,Delivery,Church Street
5410,Moto Store & CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©,Yes,No,4.2,382,080 49653126,Ulsoor,Cafe,"Wedges, Maggi, Burgers, Waffles, Margherita Pi...","Pizza, Italian, Cafe, Burger, Finger Food, Fas...",500,Delivery,Church Street
5411,Hoppipola,Yes,No,4.3,1708,+91 9620216162,Church Street,Lounge,"Masala Peanuts, Cocktails, Paratha, Pizza, Pas...","Continental, Mediterranean, European",1300,Delivery,Church Street
5417,99 Pancakes,Yes,No,4.1,41,+91 7483655827,Church Street,Dessert Parlor,Nutella Pancakes,"Desserts, Ice Cream",150,Delivery,Church Street
5418,NoLimmits Lounge and Club,Yes,Yes,4.0,2112,080 49653274,Brigade Road,Club,"Salads, Chicken Bbq Wings, Sandwiches, Pasta, ...","Chinese, Continental, North Indian, Burger, Pizza",2000,Delivery,Church Street
6021,Lassi Adda,Yes,No,4.0,65,+91 9164247999\r\n+91 9986382545,Electronic City,Beverage Shop,"Sweet Lassi, Corn Sandwich","Beverages, Sandwich, Fast Food",200,Delivery,Electronic City
7282,Cinnamon,Yes,No,3.9,450,+91 9900890054\r\n080 41201897,HSR,Casual Dining,"Raita, Tandoori Chicken, Egg Chilli, Hakka Noo...","North Indian, Chinese, Biryani",550,Delivery,HSR
8174,Sly Granny - The Community House,No,Yes,4.4,953,080 48536712\r\n080 48536715,Indiranagar,"Fine Dining, Bar","Cocktails, Pie, Rolls, Mezze Platter, Schnitze...","Modern Indian, European, American",2500,Dine-out,Indiranagar
8900,Toscano,Yes,Yes,4.5,715,080 22067757\r\n+91 7619320075,Koramangala 7th Block,Casual Dining,"Pizza, Pasta, Cocktails, Spinach Ravioli, Tira...","Italian, Salad",1500,Delivery,Jayanagar
9085,Funky Punjab,Yes,No,3.8,125,+91 8884449474,BTM,Quick Bites,"Roti, Dal Makhani, Lassi, Panneer Butter Masal...","North Indian, Chinese",400,Delivery,Jayanagar
10763,Victoria Terminus,Yes,No,2.9,54,+91 9686933734\r\n+91 9066157771,Banaswadi,Quick Bites,"Vada Pav, Kulfi, Mumbai Sandwich, Rolls, Keema...","Fast Food, Maharashtrian, Rolls",250,Delivery,Kalyan Nagar
13688,Chinita Real Mexican Food,No,No,4.5,733,+91 9591038009\r\n080 43711400,Koramangala 5th Block,Casual Dining,"Tacos, Churros, Nachos, Salad, Enchiladas, Bur...",Mexican,1200,Dine-out,Koramangala 5th Block
13846,154 Breakfast Club,Yes,Yes,4.0,1515,080 25533133,Koramangala 3rd Block,Cafe,"Pancakes, Waffles, Bbq Sandwich, Mushroom Rago...","Cafe, Continental",900,Dine-out,Koramangala 5th Block
16820,The Oriental Spice - Ashraya Hotel,Yes,No,3.9,158,080 41148989\n+91 7795612130,Infantry Road,Casual Dining,"Noodles, Lunch Buffet, Fish, Manchurian, Salad...","Chinese, Thai, Indonesian",1300,Buffet,Lavelle Road
17253,Rasovara,Yes,Yes,4.3,772,080 41738968\n+91 9886060965,Lavelle Road,Casual Dining,"Thali, Aamras, Malpua, Dal Bati, Lassi, Plain ...","Rajasthani, North Indian",1400,Dine-out,Lavelle Road
18575,Sizzling Pasto,Yes,Yes,4.1,99,080 49652891,Marathahalli,"Casual Dining, Bar","Mocktails, Brownie, Sangria, Cocktail Prawn, S...","Continental, Chinese, North Indian",1100,Dine-out,Marathahalli
18931,Red Onion,Yes,Yes,4.2,570,080 40918141\n+91 8867785004,Shanti Nagar,Casual Dining,"Fish, Dumplings, Biryani, Paneer Tikka Masala,...","Chinese, North Indian, Biryani, Kebab",1200,Delivery,MG Road
19487,Bootlegger,No,No,4.1,1545,+91 8022290099\n+91 8041462747,Lavelle Road,Pub,"Beer, Cocktails, Beef Steak, Beef Chilli, Nach...","Continental, Steak",1200,Dine-out,MG Road
19501,Ithaca - The Chancery Pavilion,No,Yes,3.9,312,+91 9902785566,Residency Road,Fine Dining,"Salads, Sunday Brunch, Cocktails, Watermelon J...","North Indian, Italian, European, Continental",2000,Dine-out,MG Road
19718,Alchemy - The Chancery Pavilion,No,Yes,4.3,485,080 49653555,Residency Road,"Microbrewery, Casual Dining","Craft Beer, Cocktails, Stout, Chicken Wings, F...",Modern Indian,2000,Drinks & nightlife,MG Road
20785,Tipsy Bull - The Bar Exchange,No,Yes,4.6,3173,080 49652910,Indiranagar,"Bar, Casual Dining","Cocktails, Peri Peri Chicken, Biryani, Mocktai...","Chinese, Continental, North Indian, Mexican",1400,Drinks & nightlife,Old Airport Road
20786,BTDT? Been There Done That,No,Yes,4.3,962,080 49652655,Indiranagar,"Bar, Casual Dining","Cocktails, Momos, Pizza, Mushroom Ragout, Roti...","European, Continental, Asian, Finger Food",1300,Drinks & nightlife,Old Airport Road
22014,ShakesBierre,No,Yes,4.4,409,080 49653253,Brigade Road,"Microbrewery, Casual Dining","Cocktails, Mocktails, Pizza, Sweet Yogurt, Juj...","Asian, Continental, European, North Indian",1500,Drinks & nightlife,Residency Road

In [23]:
df = df.drop_duplicates()

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23012 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23012 non-null  object
 1   online_order                 23012 non-null  object
 2   book_table                   23012 non-null  object
 3   rate                         23012 non-null  float64
 4   votes                        23012 non-null  int64
 5   phone                        23012 non-null  object
 6   location                     23012 non-null  object
 7   rest_type                    23012 non-null  object
 8   dish_liked                   23012 non-null  object
 9   cuisines                     23012 non-null  object
 10  approx_cost(for two people)  23012 non-null  int64
 11  listed_in(type)              23012 non-null  object
 12  listed_in(city)              23012 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 2.5+ MB

In [26]:
df.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [27]:
df.shape

(23012, 13)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23012 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23012 non-null  object
 1   online_order                 23012 non-null  object
 2   book_table                   23012 non-null  object
 3   rate                         23012 non-null  float64
 4   votes                        23012 non-null  int64
 5   phone                        23012 non-null  object
 6   location                     23012 non-null  object
 7   rest_type                    23012 non-null  object
 8   dish_liked                   23012 non-null  object
 9   cuisines                     23012 non-null  object
 10  approx_cost(for two people)  23012 non-null  int64
 11  listed_in(type)              23012 non-null  object
 12  listed_in(city)              23012 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 2.5+ MB

In [34]:
df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [38]:
df.describe()

               rate         votes  approx_cost(for two people)
count  23012.000000  23012.000000                 23012.000000
mean       3.904002    604.098688                   753.704154
std        0.426388   1116.738081                   521.191287
min        1.800000      0.000000                    40.000000
25%        3.800000    103.000000                   400.000000
50%        4.000000    224.000000                   600.000000
75%        4.200000    590.000000                  1000.000000
max        4.900000  16832.000000                  6000.000000

In [43]:
import mysql.connector

connect = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Ygn@1994",  
    database="my_project"
)

cursor = connect.cursor()

In [45]:
df = df.rename(columns={
    'approx_cost(for two people)': 'cost',
    'listed_in(type)': 'listed_type',
    'listed_in(city)': 'listed_city'
})

In [46]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines', 'cost',
       'listed_type', 'listed_city'],
      dtype='object')

In [47]:
cursor.execute("""
CREATE TABLE restaurants (
    name TEXT,
    online_order TEXT,
    book_table TEXT,
    rate FLOAT,
    votes INT,
    phone TEXT,
    location TEXT,
    rest_type TEXT,
    dish_liked TEXT,
    cuisines TEXT,
    cost INT,
    listed_type TEXT,
    listed_city TEXT
)
""")

ProgrammingError: 1050 (42S01): Table 'restaurants' already exists

In [48]:
data = [tuple(row) for row in df.to_numpy()]

cursor.executemany("""
INSERT INTO restaurants VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
""", data)

connect.commit()

In [6]:
!pip install streamlit mysql-connector-python pandas

Requirement already satisfied: streamlit in c:\users\admin\anaconda3\lib\site-packages (1.51.0)
Requirement already satisfied: mysql-connector-python in c:\users\admin\anaconda3\lib\site-packages (9.6.0)
Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (2.3.5)
Requirement already satisfied: packaging<26,>=20 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\admin\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: jinja2 in c:\users\admin\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\admin\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\admin\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\admin\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\admin\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)
Requirement already satisfied: attrs>=22.2.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)

In [10]:
import mysql.connector


conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Ygn@1994",
    database="my_project"
)


cursor = conn.cursor()


cursor.execute("DROP TABLE IF EXISTS orders")

cursor.execute("""
CREATE TABLE orders (
    order_id VARCHAR(100),
    restaurant_name TEXT,
    order_date DATE,
    order_value FLOAT,
    discount_used VARCHAR(10),
    payment_method VARCHAR(20)
)
""")


cursor.close()
conn.close()

✅ Table created

In [49]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Ygn@1994",
    database="my_project"
)

cursor = conn.cursor()

cursor.execute("SELECT COUNT(*) FROM orders")
print("Total rows:", cursor.fetchall())

cursor.execute("SELECT * FROM orders LIMIT 5")
for row in cursor.fetchall():
    print(row)

cursor.close()
conn.close()

Total rows: [(25000,)]
('8174c2af-07a4-4837-9068-1169d963e36e', 'TBC Sky Lounge', datetime.date(2025, 5, 6), 201.87, 'No', 'Card')
('0f9ddb57-4632-4a9f-9afe-1d2e41b94e32', 'KC Das - Sweet Paradise', datetime.date(2026, 1, 8), 1392.27, 'No', 'Cash')
('099deda6-8c53-41cb-abf8-00126e6b2643', 'Hotel Kadamba Veg', datetime.date(2026, 1, 22), 1358.35, 'Yes', 'UPI')
('94a6ba27-d6ef-4d10-a026-ac0c0afa8505', 'Cafe Srinidhi', datetime.date(2025, 11, 10), 782.37, 'No', 'UPI')
('216f3ec7-80a9-4d95-872f-715c37163b6d', 'Pebble', datetime.date(2025, 12, 22), 1551.09, 'Yes', 'UPI')

In [1]:
import json

with open(r'C:\Users\admin\Downloads\orders.json') as f:
    data = json.load(f)

print("Total records:", len(data))

Total records: 25000

In [4]:
import mysql.connector
import json

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Ygn@1994",
    database="my_project"
)

cursor = conn.cursor()

with open(r'C:\Users\admin\Downloads\orders.json') as f:
    data = json.load(f)

query = """
INSERT INTO orders 
(order_id, restaurant_name, order_date, order_value, discount_used, payment_method)
VALUES (%s, %s, %s, %s, %s, %s)
"""

values = [
    (
        row['order_id'],
        row['restaurant_name'],
        row['order_date'],
        row['order_value'],
        row['discount_used'],
        row['payment_method']
    )
    for row in data
]

cursor.executemany(query, values)
conn.commit()

cursor.close()
conn.close()